import 'dart:typed_data';
import 'package:flutter/services.dart';
import 'package:http/http.dart' as http;
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:ocurithm/modules/Patient/data/model/scan_records_model.dart';

class ScanPdfService {
  static Future<void> generateAndPrintPdf({
    required ScanRecord scan,
    required String patientName,
  }) async {
    final pdf = pw.Document();

    // Load fonts for better styling and Arabic support (Cairo)
    final fontData = await rootBundle.load("assets/fonts/Cairo-Regular.ttf");
    final fontBoldData = await rootBundle.load("assets/fonts/Cairo-Bold.ttf");
    final ttf = pw.Font.ttf(fontData);
    final ttfBold = pw.Font.ttf(fontBoldData);

    // Load Clinic Logo
    Uint8List? logoBytes;
    try {
      final logoData = await rootBundle.load("assets/icons/logo.png");
      logoBytes = logoData.buffer.asUint8List();
    } catch (e) {
      print("Error loading logo: $e");
    }

    // Download images
    List<Uint8List> imageBytesList = [];
    for (var file in scan.files) {
      if (file.url != null && file.url!.isNotEmpty) {
        try {
          final response = await http.get(Uri.parse(file.url!));
          if (response.statusCode == 200) {
            imageBytesList.add(response.bodyBytes);
          }
        } catch (e) {
          print("Error downloading image: $e");
        }
      }
    }

    final dateFormatter = DateFormat('MMM dd, yyyy');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        theme: pw.ThemeData.withFont(
          base: ttf,
          bold: ttfBold,
        ),
        header: (pw.Context context) {
          return pw.Container(
            alignment: pw.Alignment.centerRight,
            padding: const pw.EdgeInsets.only(bottom: 10),
            decoration: const pw.BoxDecoration(
              border: pw.Border(
                bottom: pw.BorderSide(width: 1, color: PdfColors.grey300),
              ),
            ),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                if (logoBytes != null)
                  pw.Image(pw.MemoryImage(logoBytes), width: 60, height: 60)
                else
                  pw.Text("OCURITHM",
                      style: pw.TextStyle(
                          font: ttfBold,
                          fontSize: 24,
                          color: PdfColors.blue700)),
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.end,
                  children: [
                    pw.Text("Patient Scan Report",
                        style: pw.TextStyle(font: ttfBold, fontSize: 18)),
                    pw.Text(dateFormatter.format(DateTime.now()),
                        style: const pw.TextStyle(color: PdfColors.grey)),
                  ],
                ),
              ],
            ),
          );
        },
        footer: (pw.Context context) {
          return pw.Container(
            alignment: pw.Alignment.centerRight,
            margin: const pw.EdgeInsets.only(top: 10),
            padding: const pw.EdgeInsets.only(top: 10),
            decoration: const pw.BoxDecoration(
              border: pw.Border(
                top: pw.BorderSide(width: 0.5, color: PdfColors.grey300),
              ),
            ),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text("Generated by Ocurithm App",
                    style: const pw.TextStyle(
                        fontSize: 10, color: PdfColors.grey)),
                pw.Text("Page ${context.pageNumber} of ${context.pagesCount}",
                    style: const pw.TextStyle(
                        fontSize: 10, color: PdfColors.grey)),
              ],
            ),
          );
        },
        build: (pw.Context context) => [
          pw.SizedBox(height: 20),
          // Patient & Scan Info
          pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    _buildInfoRow(ttfBold, "Patient Name:", patientName),
                    _buildInfoRow(ttfBold, "Patient ID:",
                        scan.patient?.serialNumber ?? "N/A"),
                  ],
                ),
              ),
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    _buildInfoRow(
                        ttfBold,
                        "Scan Date:",
                        scan.scanDate != null
                            ? dateFormatter.format(scan.scanDate!)
                            : "N/A"),
                    _buildInfoRow(ttfBold, "Doctor:",
                        "Dr. ${scan.doctor?.name ?? 'Unknown'}"),
                    _buildInfoRow(ttfBold, "Target Eye:", scan.eye ?? "N/A"),
                  ],
                ),
              ),
            ],
          ),
          if (scan.investigations.isNotEmpty) ...[
            pw.Divider(height: 30, color: PdfColors.grey100),
            pw.Text("Requested Investigations",
                style: pw.TextStyle(
                    font: ttfBold, fontSize: 16, color: PdfColors.blue700)),
            pw.SizedBox(height: 10),
            pw.Wrap(
              spacing: 10,
              runSpacing: 10,
              children: scan.investigations.map((investigation) {
                return pw.Container(
                  padding: const pw.EdgeInsets.symmetric(
                      horizontal: 10, vertical: 5),
                  decoration: pw.BoxDecoration(
                    color: PdfColors.grey100,
                    borderRadius: pw.BorderRadius.circular(5),
                  ),
                  child: pw.Text(
                    investigation.toUpperCase(),
                    style: pw.TextStyle(
                      fontSize: 10,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                );
              }).toList(),
            ),
          ],
          pw.Divider(height: 40, color: PdfColors.grey100),
          // Clinical Notes
          pw.Text("Clinical Notes",
              style: pw.TextStyle(
                  font: ttfBold, fontSize: 16, color: PdfColors.blue700)),
          pw.SizedBox(height: 10),
          pw.Container(
            padding: const pw.EdgeInsets.all(10),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey50,
              borderRadius: pw.BorderRadius.circular(8),
            ),
            child: pw.Text(
              scan.comment?.isNotEmpty == true
                  ? scan.comment!
                  : "No notes provided.",
              style: const pw.TextStyle(fontSize: 12),
            ),
          ),
          pw.SizedBox(height: 30),
          // Images
          if (imageBytesList.isNotEmpty) ...[
            pw.Text("Scanned Images",
                style: pw.TextStyle(
                    font: ttfBold, fontSize: 16, color: PdfColors.blue700)),
            pw.SizedBox(height: 15),
            pw.GridView(
              crossAxisCount: 2,
              childAspectRatio: 1,
              mainAxisSpacing: 10,
              crossAxisSpacing: 10,
              children: imageBytesList.map((bytes) {
                return pw.ClipRRect(
                  horizontalRadius: 8,
                  verticalRadius: 8,
                  child: pw.Image(pw.MemoryImage(bytes), fit: pw.BoxFit.cover),
                );
              }).toList(),
            ),
          ] else
            pw.Center(
              child: pw.Text("No images available for this scan.",
                  style:
                      const pw.TextStyle(color: PdfColors.grey, fontSize: 12)),
            ),
        ],
      ),
    );

    // Print the document
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name:
          "Scan_Report_${patientName}_${dateFormatter.format(scan.scanDate ?? DateTime.now())}",
    );
  }

  static pw.Widget _buildInfoRow(pw.Font boldFont, String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 4),
      child: pw.RichText(
        text: pw.TextSpan(
          children: [
            pw.TextSpan(
              text: "$label ",
              style: pw.TextStyle(font: boldFont, fontSize: 12),
            ),
            pw.TextSpan(
              text: value,
              style: const pw.TextStyle(fontSize: 12),
            ),
          ],
        ),
      ),
    );
  }
}
