import 'package:flutter/material.dart';

import '../../modules/Patient/data/model/nationality_model.dart';

Locale locale = const Locale('en');

// List of Nationality objects
final List<Nationality> nationalities = [
  const Nationality(name: "🇦🇫 Afghan", value: "AF"),
  const Nationality(name: "🇦🇱 Albanian", value: "AL"),
  const Nationality(name: "🇩🇿 Algerian", value: "DZ"),
  const Nationality(name: "🇺🇸 American", value: "US"),
  const Nationality(name: "🇦🇩 Andorran", value: "AD"),
  const Nationality(name: "🇦🇴 Angolan", value: "AO"),
  const Nationality(name: "🇦🇷 Argentine", value: "AR"),
  const Nationality(name: "🇦🇲 Armenian", value: "AM"),
  const Nationality(name: "🇦🇺 Australian", value: "AU"),
  const Nationality(name: "🇦🇹 Austrian", value: "AT"),
  const Nationality(name: "🇦🇿 Azerbaijani", value: "AZ"),
  const Nationality(name: "🇧🇭 Bahraini", value: "BH"),
  const Nationality(name: "🇧🇩 Bangladeshi", value: "BD"),
  const Nationality(name: "🇧🇾 Belarusian", value: "BY"),
  const Nationality(name: "🇧🇪 Belgian", value: "BE"),
  const Nationality(name: "🇧🇯 Beninese", value: "BJ"),
  const Nationality(name: "🇧🇹 Bhutanese", value: "BT"),
  const Nationality(name: "🇧🇴 Bolivian", value: "BO"),
  const Nationality(name: "🇧🇦 Bosnian", value: "BA"),
  const Nationality(name: "🇧🇼 Botswanan", value: "BW"),
  const Nationality(name: "🇧🇷 Brazilian", value: "BR"),
  const Nationality(name: "🇬🇧 British", value: "GB"),
  const Nationality(name: "🇧🇳 Bruneian", value: "BN"),
  const Nationality(name: "🇧🇬 Bulgarian", value: "BG"),
  const Nationality(name: "🇧🇫 Burkinabe", value: "BF"),
  const Nationality(name: "🇲🇲 Burmese", value: "MM"),
  const Nationality(name: "🇧🇮 Burundian", value: "BI"),
  const Nationality(name: "🇰🇭 Cambodian", value: "KH"),
  const Nationality(name: "🇨🇲 Cameroonian", value: "CM"),
  const Nationality(name: "🇨🇦 Canadian", value: "CA"),
  const Nationality(name: "🇨🇻 Cape Verdean", value: "CV"),
  const Nationality(name: "🇨🇫 Central African", value: "CF"),
  const Nationality(name: "🇹🇩 Chadian", value: "TD"),
  const Nationality(name: "🇨🇱 Chilean", value: "CL"),
  const Nationality(name: "🇨🇳 Chinese", value: "CN"),
  const Nationality(name: "🇨🇴 Colombian", value: "CO"),
  const Nationality(name: "🇰🇲 Comorian", value: "KM"),
  const Nationality(name: "🇨🇩 Congolese (DRC)", value: "CD"),
  const Nationality(name: "🇨🇬 Congolese (Republic)", value: "CG"),
  const Nationality(name: "🇨🇷 Costa Rican", value: "CR"),
  const Nationality(name: "🇭🇷 Croatian", value: "HR"),
  const Nationality(name: "🇨🇺 Cuban", value: "CU"),
  const Nationality(name: "🇨🇾 Cypriot", value: "CY"),
  const Nationality(name: "🇨🇿 Czech", value: "CZ"),
  const Nationality(name: "🇩🇰 Danish", value: "DK"),
  const Nationality(name: "🇩🇯 Djiboutian", value: "DJ"),
  const Nationality(name: "🇩🇴 Dominican", value: "DO"),
  const Nationality(name: "🇳🇱 Dutch", value: "NL"),
  const Nationality(name: "🇪🇨 Ecuadorian", value: "EC"),
  const Nationality(name: "🇪🇬 Egyptian", value: "EG"),
  const Nationality(name: "🇦🇪 Emirati", value: "AE"),
  const Nationality(name: "🏴󠁧󠁢󠁥󠁮󠁧󠁿 English", value: "EN"),
  const Nationality(name: "🇬🇶 Equatorial Guinean", value: "GQ"),
  const Nationality(name: "🇪🇷 Eritrean", value: "ER"),
  const Nationality(name: "🇪🇪 Estonian", value: "EE"),
  const Nationality(name: "🇪🇹 Ethiopian", value: "ET"),
  const Nationality(name: "🇫🇯 Fijian", value: "FJ"),
  const Nationality(name: "🇫🇮 Finnish", value: "FI"),
  const Nationality(name: "🇫🇷 French", value: "FR"),
  const Nationality(name: "🇬🇦 Gabonese", value: "GA"),
  const Nationality(name: "🇬🇲 Gambian", value: "GM"),
  const Nationality(name: "🇬🇪 Georgian", value: "GE"),
  const Nationality(name: "🇩🇪 German", value: "DE"),
  const Nationality(name: "🇬🇭 Ghanaian", value: "GH"),
  const Nationality(name: "🇬🇷 Greek", value: "GR"),
  const Nationality(name: "🇬🇩 Grenadian", value: "GD"),
  const Nationality(name: "🇬🇹 Guatemalan", value: "GT"),
  const Nationality(name: "🇬🇳 Guinean", value: "GN"),
  const Nationality(name: "🇬🇼 Guinea-Bissauan", value: "GW"),
  const Nationality(name: "🇬🇾 Guyanese", value: "GY"),
  const Nationality(name: "🇭🇹 Haitian", value: "HT"),
  const Nationality(name: "🇭🇳 Honduran", value: "HN"),
  const Nationality(name: "🇭🇺 Hungarian", value: "HU"),
  const Nationality(name: "🇮🇸 Icelandic", value: "IS"),
  const Nationality(name: "🇮🇳 Indian", value: "IN"),
  const Nationality(name: "🇮🇩 Indonesian", value: "ID"),
  const Nationality(name: "🇮🇷 Iranian", value: "IR"),
  const Nationality(name: "🇮🇶 Iraqi", value: "IQ"),
  const Nationality(name: "🇮🇪 Irish", value: "IE"),
  const Nationality(name: "🇮🇱 Israeli", value: "IL"),
  const Nationality(name: "🇮🇹 Italian", value: "IT"),
  const Nationality(name: "🇨🇮 Ivorian", value: "CI"),
  const Nationality(name: "🇯🇲 Jamaican", value: "JM"),
  const Nationality(name: "🇯🇵 Japanese", value: "JP"),
  const Nationality(name: "🇯🇴 Jordanian", value: "JO"),
  const Nationality(name: "🇰🇿 Kazakh", value: "KZ"),
  const Nationality(name: "🇰🇪 Kenyan", value: "KE"),
  const Nationality(name: "🇰🇮 Kiribati", value: "KI"),
  const Nationality(name: "🇰🇼 Kuwaiti", value: "KW"),
  const Nationality(name: "🇰🇬 Kyrgyz", value: "KG"),
  const Nationality(name: "🇱🇦 Lao", value: "LA"),
  const Nationality(name: "🇱🇻 Latvian", value: "LV"),
  const Nationality(name: "🇱🇧 Lebanese", value: "LB"),
  const Nationality(name: "🇱🇸 Lesotho", value: "LS"),
  const Nationality(name: "🇱🇷 Liberian", value: "LR"),
  const Nationality(name: "🇱🇾 Libyan", value: "LY"),
  const Nationality(name: "🇱🇮 Liechtenstein", value: "LI"),
  const Nationality(name: "🇱🇹 Lithuanian", value: "LT"),
  const Nationality(name: "🇱🇺 Luxembourgish", value: "LU"),
  const Nationality(name: "🇲🇰 Macedonian", value: "MK"),
  const Nationality(name: "🇲🇬 Malagasy", value: "MG"),
  const Nationality(name: "🇲🇼 Malawian", value: "MW"),
  const Nationality(name: "🇲🇾 Malaysian", value: "MY"),
  const Nationality(name: "🇲🇻 Maldivian", value: "MV"),
  const Nationality(name: "🇲🇱 Malian", value: "ML"),
  const Nationality(name: "🇲🇹 Maltese", value: "MT"),
  const Nationality(name: "🇲🇭 Marshallese", value: "MH"),
  const Nationality(name: "🇲🇷 Mauritanian", value: "MR"),
  const Nationality(name: "🇲🇺 Mauritian", value: "MU"),
  const Nationality(name: "🇲🇽 Mexican", value: "MX"),
  const Nationality(name: "🇫🇲 Micronesian", value: "FM"),
  const Nationality(name: "🇲🇩 Moldovan", value: "MD"),
  const Nationality(name: "🇲🇨 Monegasque", value: "MC"),
  const Nationality(name: "🇲🇳 Mongolian", value: "MN"),
  const Nationality(name: "🇲🇪 Montenegrin", value: "ME"),
  const Nationality(name: "🇲🇦 Moroccan", value: "MA"),
  const Nationality(name: "🇲🇿 Mozambican", value: "MZ"),
  const Nationality(name: "🇳🇦 Namibian", value: "NA"),
  const Nationality(name: "🇳🇷 Nauruan", value: "NR"),
  const Nationality(name: "🇳🇵 Nepalese", value: "NP"),
  const Nationality(name: "🇳🇿 New Zealander", value: "NZ"),
  const Nationality(name: "🇳🇮 Nicaraguan", value: "NI"),
  const Nationality(name: "🇳🇪 Nigerien", value: "NE"),
  const Nationality(name: "🇳🇬 Nigerian", value: "NG"),
  const Nationality(name: "🇰🇵 North Korean", value: "KP"),
  const Nationality(name: "🇳🇴 Norwegian", value: "NO"),
  const Nationality(name: "🇴🇲 Omani", value: "OM"),
  const Nationality(name: "🇵🇰 Pakistani", value: "PK"),
  const Nationality(name: "🇵🇼 Palauan", value: "PW"),
  const Nationality(name: "🇵🇸 Palestinian", value: "PS"),
  const Nationality(name: "🇵🇦 Panamanian", value: "PA"),
  const Nationality(name: "🇵🇬 Papua New Guinean", value: "PG"),
  const Nationality(name: "🇵🇾 Paraguayan", value: "PY"),
  const Nationality(name: "🇵🇪 Peruvian", value: "PE"),
  const Nationality(name: "🇵🇭 Philippine", value: "PH"),
  const Nationality(name: "🇵🇱 Polish", value: "PL"),
  const Nationality(name: "🇵🇹 Portuguese", value: "PT"),
  const Nationality(name: "🇶🇦 Qatari", value: "QA"),
  const Nationality(name: "🇷🇴 Romanian", value: "RO"),
  const Nationality(name: "🇷🇺 Russian", value: "RU"),
  const Nationality(name: "🇷🇼 Rwandan", value: "RW"),
  const Nationality(name: "🇰🇳 Kittitian and Nevisian", value: "KN"),
  const Nationality(name: "🇱🇨 Saint Lucian", value: "LC"),
  const Nationality(name: "🇻🇨 Saint Vincentian", value: "VC"),
  const Nationality(name: "🇼🇸 Samoan", value: "WS"),
  const Nationality(name: "🇸🇲 San Marinese", value: "SM"),
  const Nationality(name: "🇸🇹 Sao Tomean", value: "ST"),
  const Nationality(name: "🇸🇦 Saudi", value: "SA"),
  const Nationality(name: "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Scottish", value: "SC"),
  const Nationality(name: "🇸🇳 Senegalese", value: "SN"),
  const Nationality(name: "🇷🇸 Serbian", value: "RS"),
  const Nationality(name: "🇸🇨 Seychellois", value: "SC"),
  const Nationality(name: "🇸🇱 Sierra Leonean", value: "SL"),
  const Nationality(name: "🇸🇬 Singaporean", value: "SG"),
  const Nationality(name: "🇸🇰 Slovak", value: "SK"),
  const Nationality(name: "🇸🇮 Slovenian", value: "SI"),
  const Nationality(name: "🇸🇧 Solomon Islander", value: "SB"),
  const Nationality(name: "🇸🇴 Somali", value: "SO"),
  const Nationality(name: "🇿🇦 South African", value: "ZA"),
  const Nationality(name: "🇰🇷 South Korean", value: "KR"),
  const Nationality(name: "🇸🇸 South Sudanese", value: "SS"),
  const Nationality(name: "🇪🇸 Spanish", value: "ES"),
  const Nationality(name: "🇱🇰 Sri Lankan", value: "LK"),
  const Nationality(name: "🇸🇩 Sudanese", value: "SD"),
  const Nationality(name: "🇸🇷 Surinamese", value: "SR"),
  const Nationality(name: "🇸🇿 Swazi", value: "SZ"),
  const Nationality(name: "🇸🇪 Swedish", value: "SE"),
  const Nationality(name: "🇨🇭 Swiss", value: "CH"),
  const Nationality(name: "🇸🇾 Syrian", value: "SY"),
  const Nationality(name: "🇹🇼 Taiwanese", value: "TW"),
  const Nationality(name: "🇹🇯 Tajik", value: "TJ"),
  const Nationality(name: "🇹🇿 Tanzanian", value: "TZ"),
  const Nationality(name: "🇹🇭 Thai", value: "TH"),
  const Nationality(name: "🇹🇱 Timorese", value: "TL"),
  const Nationality(name: "🇹🇬 Togolese", value: "TG"),
  const Nationality(name: "🇹🇴 Tongan", value: "TO"),
  const Nationality(name: "🇹🇹 Trinidadian", value: "TT"),
  const Nationality(name: "🇹🇳 Tunisian", value: "TN"),
  const Nationality(name: "🇹🇷 Turkish", value: "TR"),
  const Nationality(name: "🇹🇲 Turkmen", value: "TM"),
  const Nationality(name: "🇹🇻 Tuvaluan", value: "TV"),
  const Nationality(name: "🇺🇬 Ugandan", value: "UG"),
  const Nationality(name: "🇺🇦 Ukrainian", value: "UA"),
  const Nationality(name: "🇺🇾 Uruguayan", value: "UY"),
  const Nationality(name: "🇺🇿 Uzbek", value: "UZ"),
  const Nationality(name: "🇻🇺 Vanuatuan", value: "VU"),
  const Nationality(name: "🇻🇦 Vatican", value: "VA"),
  const Nationality(name: "🇻🇪 Venezuelan", value: "VE"),
  const Nationality(name: "🇻🇳 Vietnamese", value: "VN"),
  const Nationality(name: "🏴󠁧󠁢󠁷󠁬󠁳󠁿 Welsh", value: "WL"),
  const Nationality(name: "🇾🇪 Yemeni", value: "YE"),
  const Nationality(name: "🇿🇲 Zambian", value: "ZM"),
  const Nationality(name: "🇿🇼 Zimbabwean", value: "ZW"),
  const Nationality(name: "🌍 Other", value: "OT"),
];
